name: Demo Workflow
env:
    Username: "Mani"
    employee id: 12345

on: 
    workflow_dispatch:
        inputs:
            Username:
                    description: 'Enter the username'
                    required: true
                    default: 'Mani'

jobs:
    Greet:
    
        runs-on: ubuntu-latest
        steps: 
        - name: Greet the world
          run: echo "hellow world"

        - name: greet the Username
          run: echo "Hello ${{ github.event.inputs.Username }}"
          