name: new task pipeline
env:
    USERNAME: "rahul"
    EMPLOYEE_ID: 12345
on: 
    workflow_dispatch:
        
    push:
        branches: [ main ]

jobs:
    Build:
    
        runs-on: ubuntu-latest
        steps: 
        - name: Greet the world
          run: echo "hellow world"

    Deploy:
        needs: Build
        runs-on: ubuntu-latest
        steps: 
        - name: Greet the world
          run: echo "hellow world"
